---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev1
  namespace: dev1
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev1-*
spec:
  releaseName: podinfo-dev1
  chart:
    git: git@github.com:raffthebuilder/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image: rafalmurban/podinfo:dev1-ky3ijhng
    replicaCount: 1
    hpa:
      enabled: false
